import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

interface User {
    id: number,
    name: string
}

const fetcher = (url: string):Promise<User[]> => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
    const URL = 'http://localhost:8080/users'
    const {data, error} = useSWR<User[]>(URL, fetcher)

    if (error) return <h1>Error</h1>
    if (!data) return <h1>Loading...</h1>
    if (data.length === 0) return <h1>データが0件です</h1>

    return (
        <div className={styles.container}>
            <Head>
                <title>Go(Echo) + Nextjs</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Go(Echo) + Next.js
                </h1>
                {data && data.map((item: User) => (
                    <>
                        <h2 key={item.id}>
                            id: {item.id}
                            {item.name}
                        </h2>
                    </>
                ))}

            </main>
        </div>
    )
}

export default Home


